#!/usr/bin/python3.7
from __future__ import annotations
import sys
import webbrowser

query = "https://www.google.com/search?q="
newwindow=1
for term in sys.argv[1:]:
    term += "+"
    query += term
query.rstrip("+")
query += "&newwindow=1"
webbrowser.open(query)
